User_Name=(str(input("enter your name")))
Roll_no=(int(input("enter the rollno")))
mark1=(int(input("enter the m1")))
mark2=(int(input("enter the m2")))
mark3=(int(input("enter the m3")))
mark4=(int(input("enter the m4")))
mark5=(int(input("enter the m5")))
average_mark_of_student=(float(mark1+mark2+mark3+mark4+mark5)/5)
print("average_mark_of_student",average_mark_of_student)
print("User_Name",User_Name)
print("Roll_no",Roll_no)
